//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seed_v1.Models.SISTEMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaBaseTelefono
    {
        public int Id { get; set; }
        public string Telefono { get; set; }
        public int Posicion { get; set; }
        public int IdPersona { get; set; }
    
        public virtual PersonaBase PersonaBase { get; set; }
    }
}
