//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seed_v1.Models.SISTEMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SesionPrivilegio
    {
        public int IdSesion { get; set; }
        public int IdPrivilegio { get; set; }
        public string CssClass { get; set; }
    
        public virtual Privilegio Privilegio { get; set; }
        public virtual Sesion Sesion { get; set; }
    }
}
