//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seed_v1.Models.SISTEMA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISTEMAEntities : DbContext
    {
        public SISTEMAEntities()
            : base("name=SISTEMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Privilegio> Privilegio { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<SesionEmpresa> SesionEmpresa { get; set; }
        public virtual DbSet<SesionPrivilegio> SesionPrivilegio { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioBitacora> UsuarioBitacora { get; set; }
        public virtual DbSet<UsuarioEmpresa> UsuarioEmpresa { get; set; }
        public virtual DbSet<UsuarioPrivilegio> UsuarioPrivilegio { get; set; }
        public virtual DbSet<PersonaBase> PersonaBase { get; set; }
        public virtual DbSet<PersonaBaseEmail> PersonaBaseEmail { get; set; }
        public virtual DbSet<PersonaBaseTelefono> PersonaBaseTelefono { get; set; }
    }
}
